/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderId = IDL.Nat;
export const RestaurantId = IDL.Nat;
export const MenuItemId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
});
export const AppUserRole = IDL.Variant({
  'customer' : IDL.Null,
  'restaurantOwner' : IDL.Null,
  'rider' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppUserRole,
});
export const OrderStatus = IDL.Variant({
  'readyForPickup' : IDL.Null,
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'createdAt' : IDL.Int,
  'riderId' : IDL.Opt(IDL.Principal),
  'restaurantId' : RestaurantId,
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDelivery' : IDL.Func([OrderId], [], []),
  'acceptRestaurantOrder' : IDL.Func([OrderId], [], []),
  'addMenuItem' : IDL.Func(
      [RestaurantId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [MenuItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([OrderId], [], []),
  'createOrUpdateRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Restaurant],
      [],
    ),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyDeliveries' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOpenRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getReadyOrdersWithoutRider' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getRestaurantMenu' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantOrders' : IDL.Func([RestaurantId], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRestaurantMenuItems' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'placeOrder' : IDL.Func(
      [RestaurantId, IDL.Vec(OrderItem), IDL.Text],
      [Order],
      [],
    ),
  'rejectRestaurantOrder' : IDL.Func([OrderId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRestaurantOpenStatus' : IDL.Func([IDL.Bool], [], []),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderId = IDL.Nat;
  const RestaurantId = IDL.Nat;
  const MenuItemId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
  });
  const AppUserRole = IDL.Variant({
    'customer' : IDL.Null,
    'restaurantOwner' : IDL.Null,
    'rider' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppUserRole });
  const OrderStatus = IDL.Variant({
    'readyForPickup' : IDL.Null,
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'createdAt' : IDL.Int,
    'riderId' : IDL.Opt(IDL.Principal),
    'restaurantId' : RestaurantId,
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDelivery' : IDL.Func([OrderId], [], []),
    'acceptRestaurantOrder' : IDL.Func([OrderId], [], []),
    'addMenuItem' : IDL.Func(
        [RestaurantId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [MenuItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([OrderId], [], []),
    'createOrUpdateRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Restaurant],
        [],
      ),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyDeliveries' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOpenRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getReadyOrdersWithoutRider' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getRestaurantMenu' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantOrders' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRestaurantMenuItems' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [RestaurantId, IDL.Vec(OrderItem), IDL.Text],
        [Order],
        [],
      ),
    'rejectRestaurantOrder' : IDL.Func([OrderId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRestaurantOpenStatus' : IDL.Func([IDL.Bool], [], []),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };