/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'customer' : null } |
  { 'restaurantOwner' : null } |
  { 'rider' : null };
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : RestaurantId,
  'category' : string,
  'price' : bigint,
}
export type MenuItemId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'createdAt' : bigint,
  'riderId' : [] | [Principal],
  'restaurantId' : RestaurantId,
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'readyForPickup' : null } |
  { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface Restaurant {
  'id' : RestaurantId,
  'owner' : Principal,
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'isOpen' : boolean,
}
export type RestaurantId = bigint;
export interface UserProfile { 'name' : string, 'role' : AppUserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDelivery' : ActorMethod<[OrderId], undefined>,
  'acceptRestaurantOrder' : ActorMethod<[OrderId], undefined>,
  'addMenuItem' : ActorMethod<
    [RestaurantId, string, string, bigint, string],
    MenuItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[OrderId], undefined>,
  'createOrUpdateRestaurant' : ActorMethod<
    [string, string, string],
    Restaurant
  >,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyDeliveries' : ActorMethod<[], Array<Order>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOpenRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getReadyOrdersWithoutRider' : ActorMethod<[], Array<Order>>,
  'getRestaurantMenu' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'getRestaurantOrders' : ActorMethod<[RestaurantId], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listRestaurantMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'placeOrder' : ActorMethod<[RestaurantId, Array<OrderItem>, string], Order>,
  'rejectRestaurantOrder' : ActorMethod<[OrderId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRestaurantOpenStatus' : ActorMethod<[boolean], undefined>,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, string, string, bigint, string, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];